ngseasy modification for lsf

diff --git a/roles/pipelines_ngseasy_scripts/files/ngseasy b/roles/pipelines_ngseasy_scripts/files/ngseasy
--- a/roles/pipelines_ngseasy_scripts/files/ngseasy
+++ b/roles/pipelines_ngseasy_scripts/files/ngseasy
@@ -30,6 +30,7 @@ set -o errexit
 ###########################################################################################
 NGSEASYVERSION="1.0-r001"
 RUNDATE=`date +"%d%m%y"`
+HOME=/nfs/users/
 
 echo -e "\n\n###########################################################################################"
 echo -e "#"
@@ -45,6 +46,17 @@ echo -e "# see the GNU General Public License for details."
 echo -e "#"
 echo -e "###########################################################################################\n\n"
 
+###########################################################################################
+## test if docker is intsalled and exit if not
+###########################################################################################
+
+command -v docker >/dev/null 2>&1 || { echo -e "\n\nDocker not installed.\n\nAborting....." >&2; exit 1; }
+echo -e "Docker Installed ok"
+echo -e "Checking Docker Version and Info\n"
+DOCKERVERSION=`docker version`
+DOCKERINFO=`docker info`
+
+echo -e "\n----\nDocker Version\n----\n${DOCKERVERSION}\n----\n"Docker Info"\n----\n${DOCKERINFO}\n----\n"
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"
 sleep 1s
 
@@ -68,9 +80,7 @@ function usage_ngseasy() {
 Program: ngseasy
 Version 1.0-r001
 Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
-
 usage:   ngseasy -c <config_file> -d <project_directory>
-
 options:  -c  STRING	configuration file
           -d  STRING	project directory
           -h  NULL	show this message
@@ -83,6 +93,7 @@ options:  -c  STRING	configuration file
 
 config_tsv=""
 project_directory=""
+MYBATCH=""
 
 ###########################################################################################
 ## get options for command line args
@@ -242,17 +253,17 @@ fi
 
 
 ###########################################################################################
-## Set up Project Dir and Fastq Files
+## 0. Set up Project Dir and Fastq Files
 ###########################################################################################
 
 logger_ngseasy "[ngseasy]:Calling ngseasy_initiate_project" ${config_run_log}
 
-	/bin/bash  ngseasy_initiate_project -c ${config_tsv} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
+	/nfs/ngseasy/bin/ngseasy_initiate_project -c ${config_tsv} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
 	wait
 
 logger_ngseasy "[ngseasy]:Calling ngseasy_initiate_fastq" ${config_run_log}
 
-	/bin/bash  ngseasy_initiate_fastq -c ${config_tsv} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
+	/nfs/ngseasy/bin/ngseasy_initiate_fastq -c ${config_tsv} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
 	wait
 
 ###########################################################################################
@@ -269,7 +280,7 @@ hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`
 if [[ "${config_tsv}" == *.batch.* ]]
 then
 	logger_ngseasy "[ngseasy]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${config_run_log}
-	CONFIG=${config_tsv}
+	FILE=${config_tsv}
 
 ###########################################################################################
 ## if header present then remove it
@@ -279,127 +290,143 @@ then
 	logger_ngseasy "[ngseasy]:[${config_tsv}] header present...gonna remove this" ${config_run_log}
 	logger_ngseasy "[ngseasy]:[cmd]:sed 1d ${config_tsv} > ${config_tsv}.tmp" ${config_run_log}
 	sed 1d ${config_tsv} > ${config_tsv}.tmp
-	CONFIG=${config_tsv}.tmp
+	FILE=${config_tsv}.tmp
 else
 	logger_ngseasy "[ngseasy]:[${config_tsv}] is seemingly perfect. Well Done" ${config_run_log}
-	CONFIG=${config_tsv}
+	FILE=${config_tsv}
 fi
 
 ###########################################################################################
 ## number of samples to run ####
 ###########################################################################################
-numsamples=`wc -l ${CONFIG} | awk '{print $1}'`
+numsamples=`wc -l ${config_tsv}.tmp | awk '{print $1}'`
 logger_ngseasy "[ngseasy]:Number of samples [$numsamples]" ${config_run_log}
 
-batchsize=$(( numsamples / 20 ))
+###########################################################################################
+## number of cores available
+###########################################################################################
+# mincpuallowed=8
+numcores=`nproc`
+logger_ngseasy "[ngseasy]:Number of available cores [$numcores]" ${config_run_log}
 
-batchsize=$(( batchsize == 0 ? 1 : batchsize ))
+###########################################################################################
+## check if number of cpu less than 2 and exit if so
+###########################################################################################
 
-logger_ngseasy "[ngseasy]:Sample batchsize: ${batchsize}" ${RUNLOG}
+if [[ "$numcores" -lt 2 ]]; then
+	logger_ngseasy "[ngseasy]:Number of available cores less than 2. Exiting " ${config_run_log}
+	sleep 1s
+	exit 1;
+fi
+
+###########################################################################################
+## muber of jobs fastqc calls allowed to run at the same  ####
+###########################################################################################
+numjobsallowed=$(expr $numcores / 2)
+logger_ngseasy "[ngseasy]:Number of FastQC Jobs allowed [$numjobsallowed] ie 2 cores per sample" ${config_run_log}
 
 ###########################################################################################
 ## split config file into batches : N samples per batch. N samples == njobs
 ###########################################################################################
-logger_ngseasy "[ngseasy]:splitting config file in to batches of at most [${batchsize}] samples" ${config_run_log}
-logger_ngseasy "[ngseasy]:[cmd]:split -d -l ${batchsize} --additional-suffix=\".batch.config.tmp\" ${config_tsv}.tmp" ${config_run_log}
-split -d -l ${batchsize} --additional-suffix=".batch.${config_tsv}.tmp" ${config_tsv}.tmp
+if [[ "$numsamples"  -gt "$numjobsallowed" ]]; then
+	logger_ngseasy "[ngseasyc]:Number samples [$numsamples] greater than number of cpu jobs allowed [$numjobsallowed]" ${config_run_log}
+	logger_ngseasy "[ngseasy]:splitting config file in to batches of at most [${numjobsallowed}] samples" ${config_run_log}
+	logger_ngseasy "[ngseasy]:[cmd]:split -d -l ${numjobsallowed} --additional-suffix=\".batch.config.tmp\" ${config_tsv}.tmp" ${config_run_log}
+	split -d -l ${numjobsallowed} --additional-suffix=".batch.${config_tsv}.tmp" ${config_tsv}.tmp
+else
+	logger_ngseasy "[ngseasy]:Number of jobs to run [$numsamples]" ${config_run_log}
+	logger_ngseasy "[ngseasy]:making [original.batch.${config_tsv}.tmp]" ${config_run_log}
+	cp -v ${config_tsv}.tmp original.batch.${config_tsv}.tmp
+fi
 
 ###########################################################################################
 ## get file names to process
 ###########################################################################################
-
+#
 logger_ngseasy "[ngseasy]: Getting config file names to process " ${config_run_log}
-batchfiles=`ls | grep batch`
+batchfiles=`ls | grep batch.${config_tsv}`
+
+###########################################################################################
+## set num running jobs counter to 0 ####
+###########################################################################################
+ndockerjobs=0
 
 ###########################################################################################
 ## loop through config files and run fastqc ####
 ###########################################################################################
 
 logger_ngseasy "[ngseasy]:START FASTQC LOOP" ${config_run_log}
-timestamp=`date "+%w%H%M%S"`
 
 for MYBATCH in `ls $batchfiles`
 do
-    RAND=`perl -e "print int(rand()*10);"`
-    logger_ngseasy "[ngseasy]:[cmd]:ngseasy_fastqc -c ${MYBATCH} -d ${project_directory}" ${config_run_log}
+	logger_ngseasy "[ngseasy]:[cmd]:ngseasy_fastqc -c ${MYBATCH} -d ${project_directory}" ${config_run_log}
 
-    ###########################################################################################
-    ## call ngseasy_fastqc
-    ###########################################################################################
-    #job_name="fastqc_${USER}_${MYBATCH}_$(date +%s)"
-    #job_name="${USER}_${MYBATCH}_${timestamp}_fastqc"    by job name
-    job_name="${timestamp}${RAND}fq"
+###########################################################################################
+## call ngseasy_fastqc
+###########################################################################################
+logger_ngseasy "[ngseasy]:Calling ngseasy_fastqc" ${config_run_log}
 
-    logger_ngseasy "[ngseasy]:Calling -c ${MYBATCH} -d ${project_directory} -j ${job_name}" ${config_run_log}
+	/nfs/ngseasy/bin/ngseasy_fastqc -c ${MYBATCH} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
 
-    /bin/bash  ngseasy_fastqc -c ${MYBATCH} -d ${project_directory} -j ${job_name} 2>&1 | tee -a  ${config_run_log}.log
+###########################################################################################
+## get number of jobs running in background
+###########################################################################################
+ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
 
-    sleep 1s
+logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs started [$ndockerjobs]" ${config_run_log}
+sleep 1s
 
-    ###################################################################################
-    ## Quality Trimming
-    ###################################################################################
-    dependency_string="ended('${job_name}')" 
-    job_name="${timestamp}${RAND}tr"
+###########################################################################################
+## while jobs still running ie not equal to 0 then sleep for 10 seconds
+###########################################################################################
+#
+logger_ngseasy "[ngseasy]:Checking for the number of running Docker FastQC jobs every 1 minute" ${config_run_log}
+logger_ngseasy "[ngseasy]:When the number of running Docker FastQC jobs hits [0], the next batch will begin" ${config_run_log}
 
-    logger_ngseasy "[ngseasy]:Calling -c ${MYBATCH} -d ${project_directory} -j ${job_name}" ${config_run_log}
+logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]" ${config_run_log}
+sleep 1s
 
-    /bin/bash  ngseasy_trimmomatic -c ${MYBATCH} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-  
-    sleep 1s
-
-    ###################################################################################
-    ## Alignment
-    ###################################################################################
-    dependency_string="ended('${job_name}')" 
-    job_name="${timestamp}${RAND}al"
-
-    logger_ngseasy "[ngseasy]:Calling -c ${MYBATCH} -d ${project_directory} -j ${job_name}" ${config_run_log}
-
-    /bin/bash  ngseasy_alignment -c ${MYBATCH} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-    sleep 1s
-
-    ###################################################################################
-    ## Indel realignment
-    ###################################################################################
-    #dependency_string="done('${job_name}')" 
-    #job_name="${USER}_${MYBATCH}_${timestamp}_realignment"
-
-    #logger_ngseasy "[ngseasy]:Calling -c ${MYBATCH} -d ${project_directory} -j ${job_name}" ${config_run_log}
-
-    #/bin/bash  ngseasy_alignment -c ${MYBATCH} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-    #sleep 1s
-
-
+while [ "${ndockerjobs}" -gt 0 ]; do
+	sleep 60s;
+	ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
+	logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]"
+done
 done
 
-#logger_ngseasy "[ngseasy]:END ngseasy_fastqc" ${config_run_log}
+###########################################################################################
+## remove docker Exited containers ####
+###########################################################################################
+ndockerjobs_running=`docker ps -a | grep fastqc | grep Exited | wc -l`;
+
+if [ "${ndockerjobs_running}" -gt 0 ]; then
+
+  logger_ngseasy "[ngseasy]:cleaning up compbio/ngseasy-fastqc:${NGSEASYVERSION} container images" ${config_run_log}
+  logger_ngseasy "[ngseasy]:[cmd]:docker rm -f \$(docker ps -a | grep fastqc  | grep Exited | awk '{print \$1}')" ${config_run_log}
+
+  docker rm -f $(docker ps -a | grep fastqc  | grep Exited | awk '{print $1}')
+
+fi
+
+logger_ngseasy "[ngseasy]:END ngseasy_fastqc" ${config_run_log}
+
 
 ###################################################################################
 ## Quality Trimming
 ###################################################################################
 
-#logger_ngseasy "[ngseasy]:Calling ngseasy_trimmomatic" ${config_run_log}
-    
-#job_name="trimmomatic_${USER}_${config_tsv}_$(date +%s)"
+logger_ngseasy "[ngseasy]:Calling ngseasy_trimmomatic" ${config_run_log}
 
-#/bin/bash  ngseasy_trimmomatic -c ${config_tsv} -d ${project_directory} -j ${job_name} -w "done('fastqc_${USER}_*')" 2>&1 | tee -a  ${config_run_log}.log
+	/nfs/ngseasy/bin/ngseasy_trimmomatic -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
-#dependency_string="done('${job_name}')"
 
 ###################################################################################
 ## Alignment
 ###################################################################################
 
-#logger_ngseasy  "[ngseasy]:Calling ngseasy_alignment"  ${config_run_log}
+logger_ngseasy  "[ngseasy]:Calling ngseasy_alignment"  ${config_run_log}
 
-#job_name="alignment_${config_tsv}_$(date +%s)"
+	/nfs/ngseasy/bin/ngseasy_alignment -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
-#/bin/bash  ngseasy_alignment -c ${config_tsv} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-#ependency_string="done('${job_name}')"
 
 ## to add: option if NCPU less than nproc or 8, 16 then call mulitple alignments at the same
 
@@ -407,37 +434,27 @@ done
 ## Indel realignment
 ###################################################################################
 
-#logger_ngseasy  "[ngseasy]:Calling ngseasy_realn"  ${config_run_log}
+logger_ngseasy  "[ngseasy]:Calling ngseasy_realn"  ${config_run_log}
 
-#job_name="realn_${config_tsv}_$(date +%s)"
+	/nfs/ngseasy/bin/ngseasy_realn -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
-#/bin/bash ngseasy_realn -c ${config_tsv} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-#dependency_string="done('${job_name}')"
 
 ###################################################################################
 ## Base Quality Score Recalibration
 ###################################################################################
 
-#logger_ngseasy  "[ngseasy]:Calling ngseasy_bsqr"  ${config_run_log}
+logger_ngseasy  "[ngseasy]:Calling ngseasy_bsqr"  ${config_run_log}
 
-#job_name="bsqr_${config_tsv}_$(date +%s)"
+	/nfs/ngseasy/bin/ngseasy_bsqr -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
-#/bin/bash ngseasy_bsqr -c ${config_tsv} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-#dependency_string="done('${job_name}')"
 
 ##################################################################################
 ## Variant calling
 ###################################################################################
 
-#job_name="variant_calling_${config_tsv}_$(date +%s)"
+logger_ngseasy  "[ngseasy]:Calling ngseasy_variant_calling"  ${config_run_log}
 
-#logger_ngseasy  "[ngseasy]:Calling ngseasy_variant_calling"  ${config_run_log}
-
-#/bin/bash ngseasy_variant_calling -c ${config_tsv} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
-
-#dependency_string="done('${job_name}')"
+  /nfs/ngseasy/bin/ngseasy_variant_calling -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
 ###################################################################################
 ## Alignment statistics
diff --git a/roles/pipelines_ngseasy_scripts/files/ngseasy_bsqr b/roles/pipelines_ngseasy_scripts/files/ngseasy_bsqr
--- a/roles/pipelines_ngseasy_scripts/files/ngseasy_bsqr
+++ b/roles/pipelines_ngseasy_scripts/files/ngseasy_bsqr
@@ -44,7 +44,7 @@ KNOWN_SNPS_OMNI=""
 KNOWN_SNPS_b138=""
 ########################################################################################################
 ## test if docker is intsalled and exit if not
-## command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## Set version and run date
@@ -56,8 +56,7 @@ NGSEASY_STEP="ngseasy_bsqr"
 ########################################################################################################
 ## docker run command
 #
-## DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
-DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"
+DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman"
 
 ########################################################################################################
 ## global logging fuction
@@ -67,15 +66,6 @@ function logger_ngseasy() {
  mylogfile=${2}
  echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
  echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
-}
-
-function touch_file() {
-  file=${1}
-  if [ ! -e "${file}" ]
-  then
-     touch ${file}
-  fi
-  echo "${file}"
 }
 
 ########################################################################################################
@@ -98,27 +88,8 @@ ngseasy_bsqr sets up the NGSeasy docker containers for Base quality score recali
 }
 
 ########################################################################################################
-## check and make ~/ngseasy_logs if needed
-#
-if [[ ! -e  ${HOME}/ngseasy_logs ]]
-then
-  mkdir ${HOME}/ngseasy_logs
-  global_run_logs="${HOME}/ngseasy_logs"
-fi
-
-########################################################################################################
-## Check options passed in.
-#
-if test -z "$2"
-then
-  logger_ngseasy "[${NGSEASY_STEP}]:ERROR:No options found"
-  ngseasy_bsqr_usage
-  exit 1
-fi
-
-########################################################################################################
 ## get options for command line args
-  while  getopts "hc:d:j:w:" opt
+  while  getopts "hc:d:" opt
   do
 
       case ${opt} in
@@ -134,15 +105,7 @@ fi
     d)
     project_directory=${OPTARG}
     ;;
-      
-    j)
-    job_name=${OPTARG}
-    ;;
-
-    w)
-    dependency=${OPTARG}
-    ;;
-    esac
+      esac
   done
 
 ########################################################################################################
@@ -191,31 +154,31 @@ fi
 
 ## check ${config_tsv}. is this a batch file or the orginal config file
 #
-logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 
 hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`
 
 if [[ "${config_tsv}" == *.batch.* ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 elif [[ "$hasheader" -eq 1 ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   sed 1d ${config_tsv} > ${config_tsv}.tmp
   RUNFILE="${config_tsv}.tmp"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 else
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 fi
 
 ########################################################################################################
 ## Read config and loop through all lines calling bsqrß docker
-#
+logger_ngseasy "[${NGSEASY_STEP}]:Reading RUNFILE [${RUNFILE}]" ${config_run_log}
 
 while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18 f19 f20 f21 f22 f23
 do
@@ -279,9 +242,6 @@ NGSUSER=$f23;
 DATE=`date +"%d%m%y"`
 
 ########################################################################################################
-## LOGFILE
-#
-
 ## check and make log directory
 #
 if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/run_logs/" ]
@@ -293,8 +253,6 @@ fi
 ## LOGFILE
 ########################################################################################################
 LOGFILE="${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${TRIM}.${BSQR}.${REALN}.${ALIGNER}.${RUNDATE}.${NGSEASY_STEP}"
-
-LOG_DIR="${PROJECT_DIR}/${PROJECT_ID}/run_logs"
 
 ########################################################################################################
 ## check and make logfile
@@ -361,7 +319,7 @@ if [[ "${GENOMEBUILD}" == "b37" ]]; then
   KNOWN_SNPS_b138=""
   DBSNP_RECAB=""
 
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_b37"
+  REFDIR="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_b37"
   GENOMEINDEX="${REFDIR}/human_g1k_v37"
   REFFASTA="${REFDIR}/human_g1k_v37.fasta"
   DBSNP_RECAB="${REFDIR}/dbsnp_138.b37.recab"
@@ -390,7 +348,7 @@ elif [[ "${GENOMEBUILD}" == "hg19" ]]; then
   KNOWN_SNPS_b138=""
   DBSNP_RECAB=""
 
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_hg19"
+  REFDIR="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_hg19"
   GENOMEINDEX="${REFDIR}/ucsc.hg19"
   REFFASTA="${REFDIR}/ucsc.hg19.fasta"
   DBSNP_RECAB="${REFDIR}/dbsnp_138.hg19.recab"
@@ -429,9 +387,7 @@ if [[ "${BSQR}" == "no-bsqr" ]]; then
 
   # Skip if set to skip
   logger_ngseasy "[${NGSEASY_STEP}]:Skipping Base quality score recalibration. BSQR set to [${BSQR}] " ${LOGFILE}
-  
-  # submit an empty job 
-  bsub -J "${job_name}" -w "${dependency}" date
+  sleep 1s
 
 ########################################################################################################
 ## BAMTUIL RECAB
@@ -464,14 +420,14 @@ elif [[ "${BSQR}" == "bam-bsqr" ]]; then
     logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM INPUT [${BAMIN}] " ${LOGFILE}
     logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM OUTPUT [${BAMOUT}] " ${LOGFILE}
 
-  # exit if cant find anything
-  else
+# exit if cant find anything
+else
 
-    logger_ngseasy "[${NGSEASY_STEP}]:ERROR: Can not find required BAM files in [${SOUT}/alignments/]. Exiting" ${LOGFILE}
-    #ls ${SOUT}/alignments/
-    sleep 1s
-    exit 1
-  fi
+  logger_ngseasy "[${NGSEASY_STEP}]:ERROR: Can not find required BAM files in [${SOUT}/alignments/]. Exiting" ${LOGFILE}
+  #ls ${SOUT}/alignments/
+  sleep 1s
+  exit 1
+fi
 
 ########################################################################################################
 ## run reacb
@@ -480,16 +436,12 @@ if [[ ! -e "${BAMOUTi}" ]]; then
 
   logger_ngseasy "[${NGSEASY_STEP}]:Run bam recab" ${LOGFILE}
 
-  CMDFILE=$(touch_file "${LOG_DIR}/bsqr.cmd")
-
-  echo "#!/bin/bash
-#
-#BSUB -J ${job_name}             
-#BSUB -q docker_queue               
-#BSUB -o ${LOGFILE}.out
-#BSUB -e ${LOGFILE}.err
-
-/bin/bash -c \"time bam recab \
+  time ${DOCKER_RUN} \
+  -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+  -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+  --name bam_recab_${BAM_PREFIX} \
+  -t compbio/ngseasy-base:${NGSEASYVERSION} /bin/bash -c \
+  "time bam recab \
   --in ${BAMIN} \
   --out -.bam \
   --refFile ${REFFASTA} \
@@ -498,26 +450,27 @@ if [[ ! -e "${BAMOUTi}" ]]; then
   --maxBaseQual 40 | \
   sambamba sort -t ${NCPU} -m 2GB --tmpdir=${SOUTDocker}/tmp -o ${BAMOUT} /dev/stdin && \
   sambamba index ${BAMOUT} && \
-  rm -rf ${SOUTDocker}/tmp/*\"" > ${CMDFILE}
-
-  LSB_DOCKER_IMAGE=compbio/ngseasy-base:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t" bsub  -w "${dependency}" < ${CMDFILE}
-
-else
-  logger_ngseasy "[${NGSEASY_STEP}]:Already run bam recab..Skipping" ${LOGFILE}
-  # submit an empty job 
-  bsub -J "${job_name}" -w "${dependency}" date
+  rm -rf ${SOUTDocker}/tmp/*"
+  wait
   sleep 1s
+## log docker run
+#
+ docker logs bam_recab_${BAM_PREFIX} >> ${LOGFILE}.log
+ docker rm -f bam_recab_${BAM_PREFIX}
+else
+   logger_ngseasy "[${NGSEASY_STEP}]:Already run bam recab..Skipping" ${LOGFILE}
+   sleep 1s
 fi
 
 ########################################################################################################
 ## GATK
 elif [[ "${BSQR}" == "gatk-bsqr" ]]; then
 
-  logger_ngseasy "[${NGSEASY_STEP}]:START Base quality score recalibration using GATK" ${LOGFILE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM I/O " ${LOGFILE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Will use Indel-realigned BAM [dupemk.gatk-realn.bam] if found. If not then raw BAM [dupemk.bam] is used" ${LOGFILE}
+    logger_ngseasy "[${NGSEASY_STEP}]:START Base quality score recalibration using GATK" ${LOGFILE}
+    logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM I/O " ${LOGFILE}
+    logger_ngseasy "[${NGSEASY_STEP}]:Will use Indel-realigned BAM [dupemk.gatk-realn.bam] if found. If not then raw BAM [dupemk.bam] is used" ${LOGFILE}
 
-  ## set bam file input and output
+## set bam file input and output
   if [[ -e "${SOUT}/alignments/${BAM_PREFIX}.dupemk.gatk-realn.bam" ]]; then
 
     BAMIN="${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.gatk-realn.bam"
@@ -539,32 +492,28 @@ elif [[ "${BSQR}" == "gatk-bsqr" ]]; then
     logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM INPUT [${BAMIN}] " ${LOGFILE}
     logger_ngseasy "[${NGSEASY_STEP}]:Setting BAM OUTPUT [${BAMOUT}] " ${LOGFILE}
 
-  # exit if cant find anything
-  else
+# exit if cant find anything
+else
 
-    logger_ngseasy "[${NGSEASY_STEP}]:ERROR: Can not find required BAM files in [${SOUT}/alignments/]. Exiting" ${LOGFILE}
-    ls ${SOUT}/alignments/
-    sleep 1s
-    exit 1
-  fi
+  logger_ngseasy "[${NGSEASY_STEP}]:ERROR: Can not find required BAM files in [${SOUT}/alignments/]. Exiting" ${LOGFILE}
+  ls ${SOUT}/alignments/
+  sleep 1s
+  exit 1
+fi
 
 ########################################################################################################
 ## run GATK BSQR
 #
-  if [[ ! -e "${BAMOUTi}" ]]; then
+if [[ ! -e "${BAMOUTi}" ]]; then
 
-    logger_ngseasy "[${NGSEASY_STEP}]:Run GATK BSQR" ${LOGFILE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Run GATK BSQR" ${LOGFILE}
 
-    CMDFILE=$(touch_file "${LOG_DIR}/bsqr.cmd") 
-
-    echo "#!/bin/bash
-#
-#BSUB -J ${job_name}             
-#BSUB -q docker_queue               
-#BSUB -o ${LOGFILE}.out
-#BSUB -e ${LOGFILE}.err
-
-/bin/bash -c \"time java -Xmx12g -Djava.io.tmpdir=${SOUTDocker}/tmp -jar /usr/local/bin/GenomeAnalysisTK.jar \
+  time ${DOCKER_RUN} \
+  -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+  -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+  --name gatk_recab_${BAM_PREFIX} \
+  -t compbio/ngseasy-gatk:${NGSEASYVERSION} /bin/bash -c \
+  "time java -Xmx12g -Djava.io.tmpdir=${SOUTDocker}/tmp -jar /usr/local/bin/GenomeAnalysisTK.jar \
   -T BaseRecalibrator \
   -nct ${NCPU} \
   -R ${REFFASTA} \
@@ -590,14 +539,16 @@ elif [[ "${BSQR}" == "gatk-bsqr" ]]; then
   -I ${BAMIN} \
   -o ${BAMOUT} && \
   sambamba index ${BAMOUT} \
-  rm -fr ${SOUTDocker}/tmp/*\"" > ${CMDFILE}
-
-  LSB_DOCKER_IMAGE=compbio/ngseasy-gatk:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t" bsub  -w "${dependency}" < ${CMDFILE}
+  rm -fr ${SOUTDocker}/tmp/*"
+  wait
+  sleep 1s
+## log docker run
+#
+ docker logs gatk_recab_${BAM_PREFIX} >> ${LOGFILE}.log
+ docker rm -f gatk_recab_${BAM_PREFIX}
 
 else
    logger_ngseasy "[${NGSEASY_STEP}]:Already run GATK BSQR..Skipping" ${LOGFILE}
-   # submit an empty job 
-   bsub -J "${job_name}" -w "${dependency}" date
    sleep 1s
 fi
 
@@ -611,7 +562,7 @@ fi
 ########################################################################################################
 ## permissions
 #
-##chmod -R 777 ${SOUT}/*
+chmod -R 777 ${SOUT}/*
 
 ## END ##
 done < ${RUNFILE}
diff --git a/roles/pipelines_ngseasy_scripts/files/ngseasy_realn b/roles/pipelines_ngseasy_scripts/files/ngseasy_realn
--- a/roles/pipelines_ngseasy_scripts/files/ngseasy_realn
+++ b/roles/pipelines_ngseasy_scripts/files/ngseasy_realn
@@ -46,7 +46,7 @@ KNOWN_SNPS_b138=""
 ########################################################################################################
 ## test if docker is intsalled and exit if not
 ########################################################################################################
-## command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## Set version and run date
@@ -58,8 +58,7 @@ NGSEASY_STEP="ngseasy_realn"
 ########################################################################################################
 ## docker run command
 ########################################################################################################
-## DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
-DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"
+DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman"
 
 ########################################################################################################
 ## global logging fuction
@@ -71,14 +70,6 @@ function logger_ngseasy() {
  echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
 }
 
-function touch_file() {
-  file=${1}
-  if [ ! -e "${file}" ]
-  then
-     touch ${file}
-  fi
-  echo "${file}"
-}
 ########################################################################################################
 ## global usage
 ########################################################################################################
@@ -110,10 +101,10 @@ fi
 ########################################################################################################
 ## get options for command line args
 ########################################################################################################
-  while  getopts "hc:d:j:w:" opt
+  while  getopts "hc:d:" opt
   do
 
-    case ${opt} in
+      case ${opt} in
     h)
     ngseasy_realn_usage #print help
     exit 0
@@ -126,15 +117,7 @@ fi
     d)
     project_directory=${OPTARG}
     ;;
-    
-    j)
-    job_name=${OPTARG}
-    ;;
-
-    w)
-    dependency=${OPTARG}
-    ;;
-    esac
+      esac
   done
 
 ########################################################################################################
@@ -194,26 +177,26 @@ fi
 
 ## check ${config_tsv}. is this a batch file or the orginal config file
 #
-logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 
 hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`
 
 if [[ "${config_tsv}" == *.batch.* ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 elif [[ "$hasheader" -eq 1 ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   sed 1d ${config_tsv} > ${config_tsv}.tmp
   RUNFILE="${config_tsv}.tmp"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 else
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 fi
 
 ########################################################################################################
@@ -297,8 +280,6 @@ fi
 ########################################################################################################
 LOGFILE="${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${TRIM}.${BSQR}.${REALN}.${ALIGNER}.${RUNDATE}.${NGSEASY_STEP}"
 
-LOG_DIR="${PROJECT_DIR}/${PROJECT_ID}/run_logs"
-
 ########################################################################################################
 ## check and make logfile
 ########################################################################################################
@@ -367,7 +348,7 @@ if [[ "${GENOMEBUILD}" == "b37" ]]; then
   KNOWN_SNPS_OMNI=""
   KNOWN_SNPS_b138=""
 
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_b37"
+  REFDIR="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_b37"
   GENOMEINDEX="${REFDIR}/human_g1k_v37"
   REFFASTA="${REFDIR}/human_g1k_v37.fasta"
   DBSNPb37="${REFDIR}/dbsnp_138.b37.recab"
@@ -394,7 +375,7 @@ elif [[ "${GENOMEBUILD}" == "hg19" ]]; then
   KNOWN_SNPS_OMNI=""
   KNOWN_SNPS_b138=""
 
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_hg19"
+  REFDIR="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_hg19"
   GENOMEINDEX="${REFDIR}/ucsc.hg19"
   REFFASTA="${REFDIR}/ucsc.hg19.fasta"
   DBSNPhg19="${REFDIR}/dbsnp_138.hg19.recab"
@@ -443,16 +424,13 @@ elif [[ "${REALN}" == "no-realn" ]]; then
 
   logger_ngseasy "[${NGSEASY_STEP}]:Skipping Indel Realignment" ${LOGFILE}
 
-  # submit an empty job 
-  bsub -J "${job_name}" -w "${dependency}" date
-
 ########################################################################################################
 ## bam-realn using glia
 #
 elif [[ "${REALN}" == "bam-realn" ]]; then
 
-  BAMIN=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam
-  BAMOUT=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam
+      BAMIN=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam
+      BAMOUT=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam
 
   logger_ngseasy "[${NGSEASY_STEP}]:START Indel Realignment using glia" ${LOGFILE}
   sleep 1s
@@ -486,51 +464,47 @@ chroms=""
 chroms=$(cut -f 1 ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed | uniq | transpose)
 logger_ngseasy "[${NGSEASY_STEP}]:chroms [${chroms}]" ${LOGFILE}
 
-CMDFILE=$(touch_file "${LOG_DIR}/realn.cmd")
-
-eecho "#!/bin/bash
+# docker run. note flags
+  time ${DOCKER_RUN} \
+  -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+  -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+  --name glia_realn_${BAM_PREFIX} \
+  -t compbio/ngseasy-glia:${NGSEASYVERSION} /bin/bash -c \
+  "sambamba view -t ${NCPU} -f bam -F \"not (unmapped or mate_is_unmapped) and mapping_quality >=0\" ${BAMIN} ${chroms} | \
+  glia -Rru -w 1000 -S 100 -Q 100 -G 4 -f ${REFFASTA} -v ${KNOWN_INDELS} | \
+  sambamba sort -t ${NCPU} -m 2GB --tmpdir=${SOUTDocker}/tmp -o ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam /dev/stdin && \
+  sambamba index ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam && \
+  sambamba flagstat -t ${NCPU} ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bam.flagstat && \
+  bedtools bamtobed -i ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam | bedtools merge > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bed && \
+  rm -rf ${SOUTDocker}/tmp/*"
+  wait
+  sleep 1s
+## log docker run
 #
-#BSUB -J ${job_name}             
-#BSUB -q docker_queue               
-#BSUB -o ${LOGFILE}.out
-#BSUB -e ${LOGFILE}.err
-
-/bin/bash -c \"sambamba view -t ${NCPU} -f bam -F 'not (unmapped or mate_is_unmapped) and mapping_quality >=0' ${BAMIN} ${chroms} | \
-glia -Rru -w 1000 -S 100 -Q 100 -G 4 -f ${REFFASTA} -v ${KNOWN_INDELS} | \
-sambamba sort -t ${NCPU} -m 2GB --tmpdir=${SOUTDocker}/tmp -o ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam /dev/stdin && \
-sambamba index ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam && \
-sambamba flagstat -t ${NCPU} ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bam.flagstat && \
-bedtools bamtobed -i ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam | bedtools merge > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bed && \
-rm -rf ${SOUTDocker}/tmp/*\"" > ${CMDFILE}
-
-LSB_DOCKER_IMAGE=compbio/ngseasy-glia:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t" bsub  -w "${dependency}" < ${CMDFILE}
+ docker logs glia_realn_${BAM_PREFIX} >> ${LOGFILE}.log
+ docker rm -f glia_realn_${BAM_PREFIX}
 
 ########################################################################################################
 ## GATK BaseRecalibrator and PrintReads
 #
 elif [[ "${REALN}" == "gatk-realn"  ]]; then
 
-BAMIN=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam
-BAMOUT=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam
+      BAMIN=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam
+      BAMOUT=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam
 
-logger_ngseasy "[${NGSEASY_STEP}]:START Indel Realignment using GATK" ${LOGFILE}
-  
+  logger_ngseasy "[${NGSEASY_STEP}]:START Indel Realignment using GATK" ${LOGFILE}
   #chroms=""
   #chroms=$(cut -f 1 ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed | uniq | transpose)
   #logger_ngseasy "[${NGSEASY_STEP}]:chroms [${chroms}]" ${LOGFILE}
 
-awk '{print $1":"$2"-"$3}' ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed > ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed.intervals
+  awk '{print $1":"$2"-"$3}' ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed > ${SOUT}/reports/${BAM_PREFIX}.dupemk.bed.intervals
 
-CMDFILE=$(touch_file "${LOG_DIR}/realn.cmd")
-
-echo "#!/bin/bash
-#
-#BSUB -J ${job_name}             
-#BSUB -q docker_queue               
-#BSUB -o ${LOGFILE}.out
-#BSUB -e ${LOGFILE}.err
-
-/bin/bash -c \"time java -Xmx12g -Djava.io.tmpdir=${SOUTDocker}/tmp -jar /usr/local/bin/GenomeAnalysisTK.jar \
+ time ${DOCKER_RUN} \
+  -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+  -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+  --name gatk_realn_${BAM_PREFIX} \
+  -t compbio/ngseasy-gatk:${NGSEASYVERSION} /bin/bash -c \
+  "time java -Xmx12g -Djava.io.tmpdir=${SOUTDocker}/tmp -jar /usr/local/bin/GenomeAnalysisTK.jar \
   -T RealignerTargetCreator \
   -nt ${NCPU} \
   -R ${REFFASTA} \
@@ -558,9 +532,13 @@ echo "#!/bin/bash
   sambamba index ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam
   sambamba flagstat -t ${NCPU} ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bam.flagstat && \
   bedtools bamtobed -i ${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.${REALN}.bam | bedtools merge > ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.${REALN}.bed && \
-  rm -rf ${SOUTDocker}/tmp/*\"" > ${CMDFILE}
-
-LSB_DOCKER_IMAGE=compbio/ngseasy-gatk:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t" bsub  -w "${dependency}" < ${CMDFILE}
+  rm -rf ${SOUTDocker}/tmp/*"
+  wait
+  sleep 1s
+## log docker run
+#
+ docker logs gatk_realn_${BAM_PREFIX} >> ${LOGFILE}.log
+ docker rm -f gatk_realn_${BAM_PREFIX}
 
 else
   logger_ngseasy "[${NGSEASY_STEP}]:ERROR: Do not recognise REALN option [${REALN}]. This should be one or [bam-realn] [gatk-realn] or [no-realn]. Exiting" ${LOGFILE}
@@ -572,7 +550,7 @@ fi
 ########################################################################################################
 ## permissions
 #
-##chmod -R 777 ${SOUT}/*
+chmod -R 777 ${SOUT}/*
 
 ## END ##
 done < ${RUNFILE}
diff --git a/roles/pipelines_ngseasy_scripts/files/ngseasy_trimmomatic b/roles/pipelines_ngseasy_scripts/files/ngseasy_trimmomatic
--- a/roles/pipelines_ngseasy_scripts/files/ngseasy_trimmomatic
+++ b/roles/pipelines_ngseasy_scripts/files/ngseasy_trimmomatic
@@ -80,18 +80,17 @@ echo -e "#######################################################################
 ########################################################################################################
 ## test if docker is intsalled and exit if not
 ########################################################################################################
-## command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; sleep 1s; exit 1; }
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; sleep 1s; exit 1; }
 
 ########################################################################################################
 ## test if image is intsalled and exit if not
 ########################################################################################################
-## docker images | grep ngseasy-trimmomatic 2>&1 || { echo "compbio/ngseasy-trimmomatic:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
+docker images | grep ngseasy-trimmomatic 2>&1 || { echo "compbio/ngseasy-trimmomatic:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## docker run command
 ########################################################################################################
-##DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
-DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"
+DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman"
 
 ########################################################################################################
 ## global logging fuction
@@ -126,7 +125,7 @@ ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngs
 ########################################################################################################
 ## get options for command line args
 ########################################################################################################
-  while  getopts "hc:d:j:w:" opt
+  while  getopts "hc:d:" opt
   do
       case ${opt} in
 	  h)
@@ -141,14 +140,6 @@ ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngs
 	  d)
 	  project_directory=${OPTARG}
 	  ;;
-
-	  j)
-      job_name=${OPTARG}
-      ;;
-
-      w)
-      dependency=${OPTARG}
-      ;;
       esac
   done
 
@@ -418,7 +409,15 @@ fi
 ########################################################################################################
 # adapter_fa : check of this is in palce and exit if not
 ########################################################################################################
-adapter_fa="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_b37/contaminant_list.fa"
+if [[ ${GENOMEBUILD} == "b37" ]]; then
+    adapter_fa="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_b37/contaminant_list.fa"
+elif [[ ${GENOMEBUILD} == "hg19" ]]; then
+    adapter_fa="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_hg19/contaminant_list.fa"
+elif [[ "${GENOMEBUILD}" == "hs37d5" ]]; then
+    adapter_fa="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_hs37d5/contaminant_list.fa"
+elif [[ "${GENOMEBUILD}" == "hs38DH" ]]; then
+    adapter_fa="/home/pipeman/ngs_projects/ngseasy_resources/reference_genomes_hs38DH/contaminant_list.fa"
+fi
 logger_ngseasy "[${NGSEASY_STEP}]:setting adaptor list docker dir [$adapter_fa]" ${LOGFILE}
 
 ########################################################################################################
@@ -463,48 +462,47 @@ if [ -s "${SOUT}/fastq/${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${TRIM}_1
 then
 	logger_ngseasy "[${NGSEASY_STEP}]:PE Trimmed Data already exists...skipping [${NGSEASY_STEP}]" ${LOGFILE}
 
-	# submit an empty job 
-	bsub -J "${job_name}" -w "${dependency}" date
-
+########################################################################################################
+## atrim
 elif [[ "$TRIM" == "atrim" ]]; then
 	logger_ngseasy "[${NGSEASY_STEP}]:Trimmomatic not run yet" ${LOGFILE}
 
 ########################################################################################################
 ## run compbio/ngseasy-trimmomatic
-#
+########################################################################################################
 logger_ngseasy "[${NGSEASY_STEP}]:START qc of raw fastq files" ${LOGFILE}
 logger_ngseasy "[${NGSEASY_STEP}]:TRIM set to [$TRIM] - adaptor trim. Adaptor and read quality trimming" ${LOGFILE}
-
-## get ngs_resource mapping
-#myresources=`dirname ${PROJECT_DIR}`
-#NGSResources="${myresources}/ngs_resources"
-
-## run trimmomatic
-#
 logger_ngseasy "[${NGSEASY_STEP}]:[cmd]: ILLUMINACLIP:${adapter_fa}:2:30:10:5:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 AVGQUAL:2 MINLEN:75 " ${LOGFILE}
-logger_ngseasy "bsub -J '${job_name}.a' -q docker_queue -o '${LOGFILE}.out' -e '${LOGFILE}.err' -w '${dependency}'..." ${LOGFILE}
 
-LSB_DOCKER_IMAGE=compbio/ngseasy-trimmomatic:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
--J "${job_name}.a" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "${dependency}" java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
-	PE \
-	-threads ${NCPU} \
-	${SOUTDocker}/fastq/${FQ1} \
-	${SOUTDocker}/fastq/${FQ2} \
-	${qcPEFQ1} ${qcSEFQ1} \
-	${qcPEFQ2} ${qcSEFQ2} \
-	ILLUMINACLIP:${adapter_fa}:2:30:10:5:true \
-	LEADING:3 \
-	TRAILING:3 \
-	SLIDINGWINDOW:4:15 \
-	AVGQUAL:2 \
-	MINLEN:75
+${DOCKER_RUN} \
+    --rm=true \
+    -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+    -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+    --name trimmomatic_${BAM_PREFIX} \
+    -t compbio/ngseasy-trimmomatic:${NGSEASYVERSION} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
+    PE \
+    -threads ${NCPU} \
+    ${SOUTDocker}/fastq/${FQ1} \
+    ${SOUTDocker}/fastq/${FQ2} \
+    ${qcPEFQ1} ${qcSEFQ1} \
+    ${qcPEFQ2} ${qcSEFQ2} \
+    ILLUMINACLIP:${adapter_fa}:2:30:10:5:true \
+    LEADING:3 \
+    TRAILING:3 \
+    SLIDINGWINDOW:4:15 \
+    AVGQUAL:2 \
+    MINLEN:75
 
 logger_ngseasy "[${NGSEASY_STEP}]:FastQC post Trimmomatic" ${LOGFILE}
 
+########################################################################################################
 ##  compbio/ngseasy-fastqc
-#
-LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
--J "${job_name}" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "ended('${job_name}.a')" /usr/local/pipeline/FastQC/fastqc \
+########################################################################################################
+	${DOCKER_RUN} \
+	--rm=true \
+	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+  	--name fastqc_post_trimm_${BAM_PREFIX} \
+	-t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc \
 	--threads 4 \
 	--extract \
 	--quiet \
@@ -517,40 +515,22 @@ LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${
 
 ########################################################################################################
 ## Just QC FASTQ NO ADAPTOR TRIM
-# btrim is basic qc-trim
-#
+## btrim is basic qc-trim
+########################################################################################################
 elif [[ "$TRIM" == "btrim" ]]; then
 
 logger_ngseasy "[${NGSEASY_STEP}]:START qc of raw fastq files" ${LOGFILE}
 logger_ngseasy "[${NGSEASY_STEP}]:TRIM set to [$TRIM] - basic trim. Just read quality trimming. No adaptor trimming" ${LOGFILE}
 
-#if [[ ! -s ${SOUT}/fastq/${FQ1}.art_filt.gz  ]] && [[ ! -s ${SOUT}/fastq/${FQ2}.art_filt.gz ]]; then
-## make parallel cmd
-#
-#echo -e "
-#zcat ${SOUTDocker}/fastq/${FQ1} | fastx_artifacts_filter -Q33 -i - -z -o ${SOUTDocker}/fastq/${FQ1}.art_filt.gz
-#zcat ${SOUTDocker}/fastq/${FQ2} | fastx_artifacts_filter -Q33 -i - -z -o ${SOUTDocker}/fastq/${FQ2}.art_filt.gz
-#" > ${SOUT}/parallel_fastx.cmd
-#
-## run fastx_artifacts_filter
-#
-#logger_ngseasy "[${NGSEASY_STEP}]:[cmd]: fastx_artifacts_filter. Removing Homopolymer reads" ${LOGFILE}
-#
-#	${DOCKER_RUN} \
-#	--rm=true \
-#	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-#	--name fastx_artifacts_filter_${BAM_PREFIX} \
-#	-t compbio/ngseasy-trimmomatic:${NGSEASYVERSION} /bin/bash -c "cat ${SOUTDocker}/parallel_fastx.cmd | parallel -j 2 --no-notice"
-#fi
-
-
-## run trimmomatic
-#
-
-logger_ngseasy "bsub -J '${job_name}.a' -q docker_queue -o '${LOGFILE}.out' -e '${LOGFILE}.err' -w '${dependency}'..." ${LOGFILE}
-
-LSB_DOCKER_IMAGE=compbio/ngseasy-trimmomatic:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
--J "${job_name}.a" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "${dependency}" java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
+########################################################################################################
+## run trimmomatic btrim
+########################################################################################################
+	${DOCKER_RUN} \
+	--rm=true \
+	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+        -v ${PROJECT_DIR}/ngseasy_resources:/home/pipeman/ngs_projects/ngseasy_resources \
+	--name trimmomatic_${BAM_PREFIX} \
+	-t compbio/ngseasy-trimmomatic:${NGSEASYVERSION} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
 	PE \
 	-threads ${NCPU} \
 	${SOUTDocker}/fastq/${FQ1} \
@@ -565,11 +545,14 @@ LSB_DOCKER_IMAGE=compbio/ngseasy-trimmomatic:${NGSEASYVERSION} LSB_DOCKER_OPTION
 
 logger_ngseasy "[${NGSEASY_STEP}]:START FastQC post Trimmomatic" ${LOGFILE}
 
+########################################################################################################
 ##  compbio/ngseasy-fastqc
-#
-LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
--J "${job_name}" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "ended('${job_name}.a')" /usr/local/pipeline/FastQC/fastqc \
-	--threads 4 \
+########################################################################################################
+	${DOCKER_RUN} \
+	--rm=true \
+	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
+	--name fastqc_post_trimm_${BAM_PREFIX} \
+	-t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc \
 	--threads 4 \
 	--extract \
 	--quiet \
@@ -580,7 +563,7 @@ LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${
 	${qcSEFQ1} \
 	${qcSEFQ2}
 
-elif [[ "${TRIM}" == "notrim" ]]; then
+elif [[ "${TRIM}" == "no-trim" ]]; then
 	logger_ngseasy "[${NGSEASY_STEP}]:Skipping quality control of raw fastq reads. NOT RECOMMENDED" ${LOGFILE}
 else
 	logger_ngseasy "[${NGSEASY_STEP}]:ERROR Do not recognise TRIM option. Should be one of [atrim] [btrim] or [no-trim]" ${LOGFILE}
@@ -590,7 +573,7 @@ fi
 ###########################################################################################
 ## permissions
 ###########################################################################################
-### chmod -R 776 ${SOUT}/*
+chmod -R 776 ${SOUT}/*
 
 ###########################################################################################
 ## THE END
