running NGSeasy: project setup

diff --git a/roles/pipelines_ngseasy_scripts/templates/ngseasy b/roles/pipelines_ngseasy_scripts/templates/ngseasy
--- a/roles/pipelines_ngseasy_scripts/templates/ngseasy
+++ b/roles/pipelines_ngseasy_scripts/templates/ngseasy
@@ -49,15 +49,15 @@ echo -e "#######################################################################
 ## test if docker is intsalled and exit if not
 ###########################################################################################
 
-command -v docker >/dev/null 2>&1 || { echo -e "\n\nDocker not installed.\n\nAborting....." >&2; exit 1; }
-echo -e "Docker Installed ok"
-echo -e "Checking Docker Version and Info\n"
-DOCKERVERSION=`docker version`
-DOCKERINFO=`docker info`
+#command -v docker >/dev/null 2>&1 || { echo -e "\n\nDocker not installed.\n\nAborting....." >&2; exit 1; }
+#echo -e "Docker Installed ok"
+#echo -e "Checking Docker Version and Info\n"
+#DOCKERVERSION=`docker version`
+#DOCKERINFO=`docker info`
 
-echo -e "\n----\nDocker Version\n----\n${DOCKERVERSION}\n----\n"Docker Info"\n----\n${DOCKERINFO}\n----\n"
-echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"
-sleep 1s
+#echo -e "\n----\nDocker Version\n----\n${DOCKERVERSION}\n----\n"Docker Info"\n----\n${DOCKERINFO}\n----\n"
+#echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"
+#sleep 1s
 
 ###########################################################################################
 ## global logging fuction
@@ -306,38 +306,40 @@ logger_ngseasy "[ngseasy]:Number of samples [$numsamples]" ${config_run_log}
 ## number of cores available
 ###########################################################################################
 # mincpuallowed=8
-numcores=`nproc`
-logger_ngseasy "[ngseasy]:Number of available cores [$numcores]" ${config_run_log}
+##numcores=`nproc`
+##logger_ngseasy "[ngseasy]:Number of available cores [$numcores]" ${config_run_log}
 
 ###########################################################################################
 ## check if number of cpu less than 2 and exit if so
 ###########################################################################################
 
-if [[ "$numcores" -lt 2 ]]; then
-	logger_ngseasy "[ngseasy]:Number of available cores less than 2. Exiting " ${config_run_log}
-	sleep 1s
-	exit 1;
-fi
+##if [[ "$numcores" -lt 2 ]]; then
+##	logger_ngseasy "[ngseasy]:Number of available cores less than 2. Exiting " ${config_run_log}
+##	sleep 1s
+##	exit 1;
+##fi
 
 ###########################################################################################
 ## muber of jobs fastqc calls allowed to run at the same  ####
 ###########################################################################################
-numjobsallowed=$(expr $numcores / 2)
-logger_ngseasy "[ngseasy]:Number of FastQC Jobs allowed [$numjobsallowed] ie 2 cores per sample" ${config_run_log}
+##numjobsallowed=$(expr $numcores / 2)
+##logger_ngseasy "[ngseasy]:Number of FastQC Jobs allowed [$numjobsallowed] ie 2 cores per sample" ${config_run_log}
 
 ###########################################################################################
 ## split config file into batches : N samples per batch. N samples == njobs
 ###########################################################################################
-if [[ "$numsamples"  -gt "$numjobsallowed" ]]; then
+##if [[ "$numsamples"  -gt "$numjobsallowed" ]]; then
 	logger_ngseasy "[ngseasyc]:Number samples [$numsamples] greater than number of cpu jobs allowed [$numjobsallowed]" ${config_run_log}
 	logger_ngseasy "[ngseasy]:splitting config file in to batches of at most [${numjobsallowed}] samples" ${config_run_log}
 	logger_ngseasy "[ngseasy]:[cmd]:split -d -l ${numjobsallowed} --additional-suffix=\".batch.config.tmp\" ${config_tsv}.tmp" ${config_run_log}
-	split -d -l ${numjobsallowed} --additional-suffix=".batch.${config_tsv}.tmp" ${config_tsv}.tmp
-else
-	logger_ngseasy "[ngseasy]:Number of jobs to run [$numsamples]" ${config_run_log}
-	logger_ngseasy "[ngseasy]:making [original.batch.${config_tsv}.tmp]" ${config_run_log}
-	cp -v ${config_tsv}.tmp original.batch.${config_tsv}.tmp
-fi
+##	split -d -l ${numjobsallowed} --additional-suffix=".batch.${config_tsv}.tmp" ${config_tsv}.tmp
+	split -d -l ${numsamples} --additional-suffix=".batch.${config_tsv}.tmp" ${config_tsv}.tmp
+
+##else
+##	logger_ngseasy "[ngseasy]:Number of jobs to run [$numsamples]" ${config_run_log}
+##	logger_ngseasy "[ngseasy]:making [original.batch.${config_tsv}.tmp]" ${config_run_log}
+##	cp -v ${config_tsv}.tmp original.batch.${config_tsv}.tmp
+##fi
 
 ###########################################################################################
 ## get file names to process
@@ -349,13 +351,15 @@ batchfiles=`ls | grep batch`
 ###########################################################################################
 ## set num running jobs counter to 0 ####
 ###########################################################################################
-ndockerjobs=0
+##ndockerjobs=0
 
 ###########################################################################################
 ## loop through config files and run fastqc ####
 ###########################################################################################
 
 logger_ngseasy "[ngseasy]:START FASTQC LOOP" ${config_run_log}
+
+job_dependencies=()
 
 for MYBATCH in `ls $batchfiles`
 do
@@ -364,48 +368,55 @@ do
 ###########################################################################################
 ## call ngseasy_fastqc
 ###########################################################################################
-logger_ngseasy "[ngseasy]:Calling ngseasy_fastqc" ${config_run_log}
+    job_name="fastqc_${MYBATCH}_$(date +%s)"
 
-	/bin/bash  ngseasy_fastqc -c ${MYBATCH} -d ${project_directory}  2>&1 | tee -a  ${config_run_log}.log
+    logger_ngseasy "[ngseasy]:Calling ngseasy_fastqc" ${config_run_log}
 
+	/bin/bash  ngseasy_fastqc -c ${MYBATCH} -d ${project_directory} -j ${job_name}   2>&1 | tee -a  ${config_run_log}.log
+     
+    job_dependencies+=("done('${job_name}')")
 ###########################################################################################
 ## get number of jobs running in background
 ###########################################################################################
-ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
+##ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
 
-logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs started [$ndockerjobs]" ${config_run_log}
+##logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs started [$ndockerjobs]" ${config_run_log}
 sleep 1s
 
 ###########################################################################################
 ## while jobs still running ie not equal to 0 then sleep for 10 seconds
 ###########################################################################################
 #
-logger_ngseasy "[ngseasy]:Checking for the number of running Docker FastQC jobs every 1 minute" ${config_run_log}
-logger_ngseasy "[ngseasy]:When the number of running Docker FastQC jobs hits [0], the next batch will begin" ${config_run_log}
+##logger_ngseasy "[ngseasy]:Checking for the number of running Docker FastQC jobs every 1 minute" ${config_run_log}
+##logger_ngseasy "[ngseasy]:When the number of running Docker FastQC jobs hits [0], the next batch will begin" ${config_run_log}
 
-logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]" ${config_run_log}
-sleep 1s
+##logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]" ${config_run_log}
+## sleep 1s
 
-while [ "${ndockerjobs}" -gt 0 ]; do
-	sleep 60s;
-	ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
-	logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]"
+##while [ "${ndockerjobs}" -gt 0 ]; do
+##	sleep 60s;
+##	ndockerjobs=`docker ps -a | grep fastqc | grep Up | wc -l`;
+##	logger_ngseasy "[ngseasy]:Number of Docker FastQC jobs running [$ndockerjobs]"
+##done
 done
-done
+
+dependency_string=$(IFS='&&' ; echo "${job_dependencies[*]}")
+
+echo ${dependency_string}
 
 ###########################################################################################
 ## remove docker Exited containers ####
 ###########################################################################################
-ndockerjobs_running=`docker ps -a | grep fastqc | grep Exited | wc -l`;
+##ndockerjobs_running=`docker ps -a | grep fastqc | grep Exited | wc -l`;
 
-if [ "${ndockerjobs_running}" -gt 0 ]; then
+##if [ "${ndockerjobs_running}" -gt 0 ]; then
 
-  logger_ngseasy "[ngseasy]:cleaning up compbio/ngseasy-fastqc:${NGSEASYVERSION} container images" ${config_run_log}
-  logger_ngseasy "[ngseasy]:[cmd]:docker rm -f \$(docker ps -a | grep fastqc  | grep Exited | awk '{print \$1}')" ${config_run_log}
+##  logger_ngseasy "[ngseasy]:cleaning up compbio/ngseasy-fastqc:${NGSEASYVERSION} container images" ${config_run_log}
+##  logger_ngseasy "[ngseasy]:[cmd]:docker rm -f \$(docker ps -a | grep fastqc  | grep Exited | awk '{print \$1}')" ${config_run_log}
 
-  docker rm -f $(docker ps -a | grep fastqc  | grep Exited | awk '{print $1}')
+##  docker rm -f $(docker ps -a | grep fastqc  | grep Exited | awk '{print $1}')
 
-fi
+##fi
 
 logger_ngseasy "[ngseasy]:END ngseasy_fastqc" ${config_run_log}
 
@@ -415,9 +426,12 @@ logger_ngseasy "[ngseasy]:END ngseasy_fastqc" ${config_run_log}
 ###################################################################################
 
 logger_ngseasy "[ngseasy]:Calling ngseasy_trimmomatic" ${config_run_log}
+    
+job_name="trimmomatic_${MYBATCH}_$(date +%s)"
 
-	/bin/bash  ngseasy_trimmomatic -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
+/bin/bash  ngseasy_trimmomatic -c ${config_tsv} -d ${project_directory} -j ${job_name} -w ${dependency_string} 2>&1 | tee -a  ${config_run_log}.log
 
+dependency_string="done('${job_name}')"
 
 ###################################################################################
 ## Alignment
@@ -425,7 +439,7 @@ logger_ngseasy "[ngseasy]:Calling ngseasy_trimmomatic" ${config_run_log}
 
 logger_ngseasy  "[ngseasy]:Calling ngseasy_alignment"  ${config_run_log}
 
-	/bin/bash  ngseasy_alignment -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
+##	/bin/bash  ngseasy_alignment -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
 
 ## to add: option if NCPU less than nproc or 8, 16 then call mulitple alignments at the same
@@ -436,7 +450,7 @@ logger_ngseasy  "[ngseasy]:Calling ngseasy_alignment"  ${config_run_log}
 
 logger_ngseasy  "[ngseasy]:Calling ngseasy_realn"  ${config_run_log}
 
-	/bin/bash ngseasy_realn -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
+##	/bin/bash ngseasy_realn -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
 
 ###################################################################################
@@ -445,7 +459,7 @@ logger_ngseasy  "[ngseasy]:Calling ngseasy_realn"  ${config_run_log}
 
 logger_ngseasy  "[ngseasy]:Calling ngseasy_bsqr"  ${config_run_log}
 
-	/bin/bash ngseasy_bsqr -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
+##	/bin/bash ngseasy_bsqr -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
 
 ##################################################################################
@@ -454,7 +468,7 @@ logger_ngseasy  "[ngseasy]:Calling ngseasy_bsqr"  ${config_run_log}
 
 logger_ngseasy  "[ngseasy]:Calling ngseasy_variant_calling"  ${config_run_log}
 
-  /bin/bash ngseasy_variant_calling -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
+##  /bin/bash ngseasy_variant_calling -c ${config_tsv} -d ${project_directory} 2>&1 | tee -a  ${config_run_log}.log
 
 ###################################################################################
 ## Alignment statistics
diff --git a/roles/pipelines_ngseasy_scripts/templates/ngseasy_fastqc b/roles/pipelines_ngseasy_scripts/templates/ngseasy_fastqc
--- a/roles/pipelines_ngseasy_scripts/templates/ngseasy_fastqc
+++ b/roles/pipelines_ngseasy_scripts/templates/ngseasy_fastqc
@@ -79,17 +79,19 @@ echo -e "#######################################################################
 ########################################################################################################
 ## test if docker is intsalled and exit if not
 ########################################################################################################
-command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+## command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## test if image is intsalled and exit if not
 ########################################################################################################
-docker images | grep ngseasy-fastqc 2>&1 || { echo "compbio/ngseasy-fastqc:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
+## docker images | grep ngseasy-fastqc 2>&1 || { echo "compbio/ngseasy-fastqc:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## docker run command
 ########################################################################################################
-DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
+## DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
+## DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
+DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"
 
 ########################################################################################################
 ## global logging fuction
@@ -124,7 +126,7 @@ This is is optomised for PE data, and calls 2 threads as default to process the 
 ########################################################################################################
 ## get options for command line args
 ########################################################################################################
-  while  getopts "hc:d:" opt
+  while  getopts "hc:d:j:" opt
   do
 
       case ${opt} in
@@ -140,6 +142,10 @@ This is is optomised for PE data, and calls 2 threads as default to process the 
 	  d)
 	  project_directory=${OPTARG}
 	  ;;
+
+	  j)
+      job_name=${OPTARG}
+      ;;
       esac
   done
 ###########################################################################################
@@ -153,21 +159,6 @@ if [[ -z "$config_tsv" ]]; then
     sleep 1s
     exit 1
 fi
-########################################################################################################
-## check config file exists.
-########################################################################################################
-if [[ ! -e "${config_tsv}" ]]
-then
-	    logger_ngseasy "[${NGSEASY_STEP}]:ERROR : [${config_tsv}] does not exist....exiting "
-	    ngseasy_fastqc_usage;
-	    exit 1;
-else
-	    logger_ngseasy "[${NGSEASY_STEP}]:Configuration file found [${config_tsv}] "
-	    if [[ ! -e ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}.log ]]
-	    then
-	    touch ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}.log
-	    fi
-fi
 
 ########################################################################################################
 ## check project_directory exists.
@@ -180,6 +171,23 @@ if [[ ! -d "${project_directory}" ]]
 else
 	    logger_ngseasy "[${NGSEASY_STEP}]:Top Level Project Directory [${project_directory}] "
 fi
+
+########################################################################################################
+## check config file exists.
+########################################################################################################
+if [[ ! -e "${config_tsv}" ]]
+then
+	    logger_ngseasy "[${NGSEASY_STEP}]:ERROR : [${config_tsv}] does not exist....exiting "
+	    ngseasy_fastqc_usage;
+	    exit 1;
+else
+	    logger_ngseasy "[${NGSEASY_STEP}]:Configuration file found [${config_tsv}] "
+	    if [[ ! -e ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}.log ]]
+	    then
+	    touch ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}.log
+	    fi
+fi
+
 
 ###########################################################################################
 ## check Num feilds in  ${config_tsv}
@@ -203,26 +211,26 @@ fi
 ###########################################################################################
 ## check ${config_tsv}. is this a batch file or the orginal config file
 #
-logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 
 hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`
 
 if [[ "${config_tsv}" == *.batch.* ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 elif [[ "$hasheader" -eq 1 ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   sed 1d ${config_tsv} > ${config_tsv}.tmp
   RUNFILE="${config_tsv}.tmp"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 else
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 fi
 
 ###########################################################################################
@@ -259,6 +267,7 @@ DATE=`date +"%d%m%y"`
 ## LOGFILE
 ###########################################################################################
 LOGFILE="${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${TRIM}.${BSQR}.${REALN}.${ALIGNER}.${RUNDATE}.ngseasy_fastqc"
+DEPENDENCY_FILE="${PROJECT_DIR}/${PROJECT_ID}/run_logs/dependency.ngseasy_fastqc.${RUNDATE}"
 
 ########################################################################################################
 ## check and make logfile
@@ -473,14 +482,10 @@ BAM_PREFIX="${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${NGS_PLATFORM}.${TR
 ## call docker: run as -d in background (-d does not work with --rm=true).
 ## This runs all containers in background..simultaneuously!
 #
-logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:docker run -d -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman --name fastqc_${BAM_PREFIX} -t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc --threads 2 --extract --outdir ${SOUTDocker}/fastq ${SOUTDocker}/fastq/${FQ1} ${SOUTDocker}/fastq/${FQ2}" ${LOGFILE}
+logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:docker run -d -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -w /home/pipeman -e HOME=/home/pipeman --name fastqc_${BAM_PREFIX} -t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc --threads 2 --extract --outdir ${SOUTDocker}/fastq ${SOUTDocker}/fastq/${FQ1} ${SOUTDocker}/fastq/${FQ2}" ${LOGFILE}
 
-	${DOCKER_RUN} \
-	-d \
-	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-	--name fastqc_${BAM_PREFIX} \
-	-t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc --threads 2 --extract \
-	--dir ${SOUTDocker}/tmp --outdir ${SOUTDocker}/fastq ${SOUTDocker}/fastq/${FQ1} ${SOUTDocker}/fastq/${FQ2}
+LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects"  bsub \
+-J "${job_name}" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" /usr/local/pipeline/FastQC/fastqc --threads 2 --extract --dir ${SOUTDocker}/tmp --outdir ${SOUTDocker}/fastq ${SOUTDocker}/fastq/${FQ1} ${SOUTDocker}/fastq/${FQ2}
 
 ###########################################################################################
 ## QUIT IF no-fastqc option is selected
@@ -495,10 +500,12 @@ fi
 ###########################################################################################
 ## permissions
 ###########################################################################################
-chmod -R 776 ${SOUT}/*
+## chmod -R 776 ${SOUT}/*
 
 ###########################################################################################
 ## THE END
 ###########################################################################################
 done < ${RUNFILE}
 logger_ngseasy " END:FastQC on raw Fastq files " ${LOGFILE}
+
+echo "fastqc_${BAM_PREFIX}" >> ${DEPENDENCY_FILE}
diff --git a/roles/pipelines_ngseasy_scripts/templates/ngseasy_trimmomatic b/roles/pipelines_ngseasy_scripts/templates/ngseasy_trimmomatic
--- a/roles/pipelines_ngseasy_scripts/templates/ngseasy_trimmomatic
+++ b/roles/pipelines_ngseasy_scripts/templates/ngseasy_trimmomatic
@@ -80,17 +80,18 @@ echo -e "#######################################################################
 ########################################################################################################
 ## test if docker is intsalled and exit if not
 ########################################################################################################
-command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; sleep 1s; exit 1; }
+## command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; sleep 1s; exit 1; }
 
 ########################################################################################################
 ## test if image is intsalled and exit if not
 ########################################################################################################
-docker images | grep ngseasy-trimmomatic 2>&1 || { echo "compbio/ngseasy-trimmomatic:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
+## docker images | grep ngseasy-trimmomatic 2>&1 || { echo "compbio/ngseasy-trimmomatic:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## docker run command
 ########################################################################################################
-DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
+##DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
+DOCKER_OPTS="--rm -P -w /home/pipeman -e HOME=/home/pipeman"
 
 ########################################################################################################
 ## global logging fuction
@@ -125,7 +126,7 @@ ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngs
 ########################################################################################################
 ## get options for command line args
 ########################################################################################################
-  while  getopts "hc:d:" opt
+  while  getopts "hc:d:j:w:" opt
   do
       case ${opt} in
 	  h)
@@ -140,6 +141,14 @@ ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngs
 	  d)
 	  project_directory=${OPTARG}
 	  ;;
+
+	  j)
+      job_name=${OPTARG}
+      ;;
+
+      w)
+      dependency=${OPTARG}
+      ;;
       esac
   done
 
@@ -204,26 +213,26 @@ fi
 
 ## check ${config_tsv}. is this a batch file or the orginal config file
 #
-logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+logger_ngseasy "[${NGSEASY_STEP}]:Checking [${config_tsv}] format" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 
 hasheader=`sed 1q ${config_tsv} | grep PROJECT_ID | wc -l | awk '{print $1}'`
 
 if [[ "${config_tsv}" == *.batch.* ]]
 then
-  logger_ngseasy "[ngseasy_trimmomatic}:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[ngseasy_trimmomatic}:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[ngseasy_trimmomatic}:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 elif [[ "$hasheader" -eq 1 ]]
 then
-  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${config_tsv}] header present. Removing this" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
   sed 1d ${config_tsv} > ${config_tsv}.tmp
   RUNFILE="${config_tsv}.tmp"
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 else
   RUNFILE="${config_tsv}"
-  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
-  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:[${RUNFILE}] is seemingly perfect" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
+  logger_ngseasy "[${NGSEASY_STEP}]:Setting RUNFILE to [${RUNFILE}]" ${project_directory}/run_logs/ngseasy.${config_tsv}.${RUNDATE}
 fi
 
 ########################################################################################################
@@ -471,12 +480,8 @@ NGSResources="${myresources}/ngs_resources"
 #
 logger_ngseasy "[${NGSEASY_STEP}]:[cmd]: ILLUMINACLIP:${adapter_fa}:2:30:10:5:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 AVGQUAL:2 MINLEN:75 " ${LOGFILE}
 
-	${DOCKER_RUN} \
-	--rm=true \
-	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-	-v ${NGSResources}:/home/pipeman/ngs_resources \
-	--name trimmomatic_${BAM_PREFIX} \
-	-t compbio/ngseasy-trimmomatic:${NGSEASYVERSION} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
+LSB_DOCKER_IMAGE=compbio/ngseasy-trimmomatic:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -v ${NGSResources}:/home/pipeman/ngs_resources -t"  bsub \
+-J "${job_name}.a" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w ${dependency} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
 	PE \
 	-threads ${NCPU} \
 	${SOUTDocker}/fastq/${FQ1} \
@@ -494,11 +499,8 @@ logger_ngseasy "[${NGSEASY_STEP}]:FastQC post Trimmomatic" ${LOGFILE}
 
 ##  compbio/ngseasy-fastqc
 #
-	${DOCKER_RUN} \
-	--rm=true \
-	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-	--name fastqc_post_trimm_${BAM_PREFIX} \
-	-t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc \
+LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
+-J "${job_name}" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "done('${job_name}.a')" /usr/local/pipeline/FastQC/fastqc \
 	--threads 4 \
 	--extract \
 	--quiet \
@@ -540,11 +542,8 @@ logger_ngseasy "[${NGSEASY_STEP}]:TRIM set to [$TRIM] - basic trim. Just read qu
 
 ## run trimmomatic
 #
-	${DOCKER_RUN} \
-	--rm=true \
-	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-	--name trimmomatic_${BAM_PREFIX} \
-	-t compbio/ngseasy-trimmomatic:${NGSEASYVERSION} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
+LSB_DOCKER_IMAGE=compbio/ngseasy-trimmomatic:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -v ${NGSResources}:/home/pipeman/ngs_resources -t"  bsub \
+-J "${job_name}.a" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w ${dependency} java -XX:ParallelGCThreads=1 -jar /usr/local/pipeline/Trimmomatic-0.32/trimmomatic-0.32.jar \
 	PE \
 	-threads ${NCPU} \
 	${SOUTDocker}/fastq/${FQ1} \
@@ -561,11 +560,9 @@ logger_ngseasy "[${NGSEASY_STEP}]:START FastQC post Trimmomatic" ${LOGFILE}
 
 ##  compbio/ngseasy-fastqc
 #
-	${DOCKER_RUN} \
-	--rm=true \
-	-v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
-	--name fastqc_post_trimm_${BAM_PREFIX} \
-	-t compbio/ngseasy-fastqc:${NGSEASYVERSION} /usr/local/pipeline/FastQC/fastqc \
+LSB_DOCKER_IMAGE=compbio/ngseasy-fastqc:${NGSEASYVERSION} LSB_DOCKER_OPTIONS="${DOCKER_OPTS} -v ${PROJECT_DIR}:/home/pipeman/ngs_projects -t"  bsub \
+-J "${job_name}" -q docker_queue -o "${LOGFILE}.out" -e "${LOGFILE}.err" -w "done('${job_name}.a')" /usr/local/pipeline/FastQC/fastqc \
+	--threads 4 \
 	--threads 4 \
 	--extract \
 	--quiet \
@@ -586,7 +583,7 @@ fi
 ###########################################################################################
 ## permissions
 ###########################################################################################
-chmod -R 776 ${SOUT}/*
+### chmod -R 776 ${SOUT}/*
 
 ###########################################################################################
 ## THE END
